#ifndef SYSTEM_DEFINITION_H_
#define SYSTEM_DEFINITION_H_

//#define SHARED_PTR_CACHE_CHANGE
//#define	NULL_POINTER_EXCEPTION_DEBUGGING_MODE

#define	READER_PROXY_CACHE_SIZE_MAX			100
#define WRITER_PROXY_CACHE_SIZE_MAX			100
#define	RECEIVING_QUEUE_CHECKING_DURATION	100

#endif

